### ISSUE TITLE
Core - ის განახლება

### ISSUE THREAD

**Issue by otarza** [bitcamp-ge/bitcamp-platform#14]
- [x] Drupal core - ის ბოლო ვერსიამდე განახლება. 
      Drupal 9 - მდე განახლება თუ არ გამოვა, უნდა ვიპოვოთ მიზეზები და ცალკე Issue - ები გავხსნათ ამ მიზეზების აღმოსაფხვრელად.
      Drupal 9 თუ არ გამოდის ამ ეტაპზე, Drupal 8 - ს ბოლო ვერსიამდე განახლება.
- [x] საიტის გატესტვა განახლების შემდეგ.

**Comment by zzkurtanidze** [comment]
ავიღებ ამ თასქს

**Comment by otarza** [comment]
@zura12337 ძალიან კარგი, შეგიძლია დაიწყო, მოგაესაინე :muscle:

**Comment by otarza** [comment]
@zura12337 - #16 - ი დამერჯილია რაც ნიშნავს რომ ეს ტასკი დასრულებულია.

შენი ანგარიშის ნომერი გამომიგზავნე ელ.ფოსტაზე oto.zakalashvili@gmail.om - Subject - ში მიუთითე: `bitcamp-ge/bitcamp-platform#14 task completed`.

წერილის ტექსტში მიუთითე ამ ტასკის ბმული.

ეს ტასკი დაიხურება ტრანზაქციის შესრულებისთანავე.

**Comment by otarza** [comment]
ტრანზაქცია შესრულებულია, დაიხურება დადასტურებისთანავე:

![D01C6E7C-BEFE-4229-8E1B-2F3160248A2E](https://user-images.githubusercontent.com/1330491/106723445-8ddd2880-6620-11eb-83f5-2180c6b1a9a5.jpeg)

**Comment by zzkurtanidze** [comment]
ვადასტურებ რომ ჩაირიცხა.

**Comment by otarza** [comment]
@zura12337 მადლობა.
