### ISSUE TITLE
CI - პროცესის აწყობა

### ISSUE THREAD

**Issue by otarza** [bitcamp-ge/bitcamp-platform#15]
- [x] TravisCI ან CircleCI - ზე ბრენჩების ავტომატური გაბილდვა;
- [x] coding standard - ებზე შემოწმება (CodeSniffer);
- [x] ტესტების გაშვება;

**Comment by George1Meshveliani** [comment]
ავიღებ ამ თასქს

**Comment by George1Meshveliani** [comment]
@otarza

**Comment by ABGEO** [comment]
@otarza ჰოლა. შემიძლია ამ თასქზე დახმარება.

**Comment by otarza** [comment]
@ABGEO მშვენირი, მადლობა რომ გამომეხმაურე, შეგიძლია დაიწყო. Slack - შიც მოგიწვევ თუ კითხვები გექნება.

**Comment by otarza** [comment]
@ABGEO დავმერჯე :tada: 

შენი ანგარიშის ნომერი გამომიგზავნე ამ მისამართზე: oto.zakalashvili@gmail.com
Subject - ში მიუთითე `bitcamp-ge/bitcamp-platform#15 task completed`
ტექსტში ასევე მიუთითე ამ იშუს ბმული: `https://github.com/bitcamp-ge/bitcamp-platform/issues/15`

**Comment by otarza** [comment]
ტრანზაქცია დასრულებულია:
![3CE23030-5CDD-4CF9-9206-0F5B4528952E](https://user-images.githubusercontent.com/1330491/106886566-7758cf00-66fd-11eb-945a-166a527f0937.jpeg)
