### ISSUE TITLE
სწრაფი ძებნა პირველი ეტაპის მომხმარებლების სიაში

### ISSUE THREAD

**Issue by otarza** [bitcamp-ge/bitcamp-platform#2]
მენეჯერებს სწრაფი ძებნისთვის დამატებით სჭირდებათ ფილტრები და საძიებო ველები:

- [x] სახელით და გვარით
- [x] ელ.ფოსტით
- [x] მომხმარებლის სახელით

**Comment by nNabakhteveli** [comment]
მომხმარებლის სახელზე მისი codehs-ის პროფილის ლინკის მიბმა უფრო სწრაფად მოძებნისთვის და დარეგისტრირებისას შესაბამისი ახალი ინპუტის ველის დამატება
